version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: sopa_postgres_dev
    environment:
      POSTGRES_DB: sopa_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sopa_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sopa_network

  # FastAPI Application - Development
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: sopa_api_dev
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/sopa_dev
      ALLOWED_HOSTS: "*"
      PROJECT_NAME: "SOPA API - Development"
      NEON_DATABASE_URL: ${NEON_DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sopa_network
    restart: unless-stopped

  # Redis for caching (optional but recommended)
  redis:
    image: redis:7-alpine
    container_name: sopa_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - sopa_network

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  sopa_network:
    driver: bridge
